#### 异常的语法：

1. try/except	`捕捉由python或你引起的异常并恢复。`
2. try/finally	`无论异常是否发生，执行清理行为`
3. raise		`手动在代码触发异常。`
4. assert		`有条件地在程序代码中触发异常。`
5. with/as		`在python2.6和后续版本中实现环境管理器。`

###一些内建的异常：

<table>
	<tr>
		<td>Exception</td>
		<td>所有异常的基类</td>
	</tr>
	<tr>
		<td>AttributeError</td>
		<td>特性引用或复制失败时引发</td>
	</tr>
	<tr>
		<td>IOError</td>
		<td>试图打开不存在文件（包括其他情况）时引发</td>
	</tr>
	<tr>
		<td>IndexError</td>
		<td>在使用序列中不存在的索引时引发</td>
	</tr>
	<tr>
		<td>KeyError</td>
		<td>在使用映射中不存在的键时引发</td>
	</tr>
	<tr>
		<td>NameError</td>
		<td>在找不到名字（变量）时引发</td>
	</tr>
	<tr>
		<td>SyntaxError</td>
		<td>在代码为错误形式时引发</td>
	</tr>
	<tr>
		<td>TypeError</td>
		<td>在内建操作或者函数应用于错误类型的对象，但是对象使用不合适的值引发</td>
	</tr>
	<tr>
		<td>ValueError</td>
		<td>在内建操作或者函数应用于正确类型的对象，但是该对象使用不合适的值时引发</td>
	</tr>
	<tr>
		<td>ZeroDivisionError</td>
		<td>在除法或者模除操作的第二个参数为0时引发</td>
	</tr>
</table>
		

	

----


使用try捕捉异常
-
	def fetcher(obj,index):
		return obj[index]

	x = 'spam'
	try：
		fetcher(x,10)
	except IndexError:
		print 'got exception'

使用try/finally组合
- 
在finally里定义的语句不管是否发生了异常都会执行。

	try：
		fetcher(x,10)
	except IndexError:
		print 'got exception'
	finally:
		print 'fetch'
		
## except

空的except会捕捉所有的异常，如果要捕捉指定的异常则在except后面跟异常类型。

也可以用多个except来捕捉不同的错误来进行处理。

一个except也可以捕捉多个类型。

	try:
		x = input('Enter the first: ')
    	y = input('Enter the second: ')
    	print x / y
	except:
		print 'all'


	try:
		x = input('Enter the first: ')
    	y = input('Enter the second: ')
    	print x / y
	except NameError:
		print 'Name'
	except TypeError:
		print 'Name'

	try:
		x = input('Enter the first: ')
    	y = input('Enter the second: ')
    	print x / y
	except (NameError,TypeError):
		print 'Name,type'


else
-
 在try中使用else会在没有异常时执行，在需要没有异常时才执行的语句时else很有用，如果在try/except执行后的语句虽然也会执行到，但是你不知道是发生了异常但是处理了还是没有发生异常执行到这块语句的。


	try：
		fetcher(x,10)
	except:
		print 'got except'
	else:
		print 'no except'

raise使用：故意触发异常
-
为了引发异常，可以使用一个类（应该是Exception的子类）或实例参数调用raise语句。

使用类时，程序会自动创建实例。
	
	raise Exception
	raise Exception('hyperdrive overload')

第一个例子引发了一个没有任何有关错误信息的普通异常。

第二个例子添加了一些hyperdrive overload的错误信息。

#### 自定义异常类

继承`Exception`类

	class someCustomException(Exception):pass

assert 语句
-
`assert <test>,<data>`,如果test为假则，python就会引发异常：data项（如果提供了的话）是异常的额外数据。